/* Generated by Yosys 0.38 (git sha1 543faed9c8c, clang++ 17.0.6 -fPIC -Os) */

module pwm_ctrl(clk, rst, duty, pwm_out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  input clk;
  wire clk;
  wire \counter[0] ;
  wire \counter[1] ;
  wire \counter[2] ;
  wire \counter[3] ;
  wire \counter[4] ;
  wire \counter[5] ;
  wire \counter[6] ;
  wire \counter[7] ;
  input [7:0] duty;
  wire [7:0] duty;
  output pwm_out;
  wire pwm_out;
  input rst;
  wire rst;
  sky130_fd_sc_hd__inv_2 _44_ (
    .A(duty[4]),
    .Y(_08_)
  );
  sky130_fd_sc_hd__inv_2 _45_ (
    .A(duty[6]),
    .Y(_09_)
  );
  sky130_fd_sc_hd__or2b_2 _46_ (
    .A(\counter[7] ),
    .B_N(duty[7]),
    .X(_10_)
  );
  sky130_fd_sc_hd__or2b_2 _47_ (
    .A(\counter[5] ),
    .B_N(duty[5]),
    .X(_11_)
  );
  sky130_fd_sc_hd__or2b_2 _48_ (
    .A(\counter[4] ),
    .B_N(duty[4]),
    .X(_12_)
  );
  sky130_fd_sc_hd__o2111ai_2 _49_ (
    .A1(\counter[6] ),
    .A2(_09_),
    .B1(_10_),
    .C1(_11_),
    .D1(_12_),
    .Y(_13_)
  );
  sky130_fd_sc_hd__and2b_2 _50_ (
    .A_N(duty[7]),
    .B(\counter[7] ),
    .X(_14_)
  );
  sky130_fd_sc_hd__inv_2 _51_ (
    .A(duty[5]),
    .Y(_15_)
  );
  sky130_fd_sc_hd__a22o_2 _52_ (
    .A1(\counter[6] ),
    .A2(_09_),
    .B1(\counter[5] ),
    .B2(_15_),
    .X(_16_)
  );
  sky130_fd_sc_hd__a2111oi_2 _53_ (
    .A1(_08_),
    .A2(\counter[4] ),
    .B1(_13_),
    .C1(_14_),
    .D1(_16_),
    .Y(_17_)
  );
  sky130_fd_sc_hd__inv_2 _54_ (
    .A(\counter[0] ),
    .Y(_18_)
  );
  sky130_fd_sc_hd__and2b_2 _55_ (
    .A_N(\counter[3] ),
    .B(duty[3]),
    .X(_19_)
  );
  sky130_fd_sc_hd__and2b_2 _56_ (
    .A_N(duty[3]),
    .B(\counter[3] ),
    .X(_20_)
  );
  sky130_fd_sc_hd__xor2_2 _57_ (
    .A(\counter[2] ),
    .B(duty[2]),
    .X(_21_)
  );
  sky130_fd_sc_hd__or3_2 _58_ (
    .A(_19_),
    .B(_20_),
    .C(_21_),
    .X(_22_)
  );
  sky130_fd_sc_hd__or2b_2 _59_ (
    .A(\counter[1] ),
    .B_N(duty[1]),
    .X(_23_)
  );
  sky130_fd_sc_hd__or2b_2 _60_ (
    .A(duty[1]),
    .B_N(\counter[1] ),
    .X(_24_)
  );
  sky130_fd_sc_hd__o211ai_2 _61_ (
    .A1(duty[0]),
    .A2(_18_),
    .B1(_23_),
    .C1(_24_),
    .Y(_25_)
  );
  sky130_fd_sc_hd__a211oi_2 _62_ (
    .A1(duty[0]),
    .A2(_18_),
    .B1(_22_),
    .C1(_25_),
    .Y(_26_)
  );
  sky130_fd_sc_hd__o21a_2 _63_ (
    .A1(\counter[6] ),
    .A2(_09_),
    .B1(_10_),
    .X(_27_)
  );
  sky130_fd_sc_hd__a21oi_2 _64_ (
    .A1(_27_),
    .A2(_16_),
    .B1(_14_),
    .Y(_28_)
  );
  sky130_fd_sc_hd__and2_2 _65_ (
    .A(_13_),
    .B(_28_),
    .X(_29_)
  );
  sky130_fd_sc_hd__nor3b_2 _66_ (
    .A(\counter[2] ),
    .B(_20_),
    .C_N(duty[2]),
    .Y(_30_)
  );
  sky130_fd_sc_hd__a21oi_2 _67_ (
    .A1(_23_),
    .A2(_25_),
    .B1(_22_),
    .Y(_31_)
  );
  sky130_fd_sc_hd__o31a_2 _68_ (
    .A1(_19_),
    .A2(_30_),
    .A3(_31_),
    .B1(_17_),
    .X(_32_)
  );
  sky130_fd_sc_hd__o2bb2a_2 _69_ (
    .A1_N(_17_),
    .A2_N(_26_),
    .B1(_29_),
    .B2(_32_),
    .X(pwm_out)
  );
  sky130_fd_sc_hd__nor2_2 _70_ (
    .A(\counter[0] ),
    .B(rst),
    .Y(_00_)
  );
  sky130_fd_sc_hd__a21oi_2 _71_ (
    .A1(\counter[1] ),
    .A2(\counter[0] ),
    .B1(rst),
    .Y(_33_)
  );
  sky130_fd_sc_hd__o21a_2 _72_ (
    .A1(\counter[1] ),
    .A2(\counter[0] ),
    .B1(_33_),
    .X(_01_)
  );
  sky130_fd_sc_hd__a21oi_2 _73_ (
    .A1(\counter[1] ),
    .A2(\counter[0] ),
    .B1(\counter[2] ),
    .Y(_34_)
  );
  sky130_fd_sc_hd__a31o_2 _74_ (
    .A1(\counter[2] ),
    .A2(\counter[1] ),
    .A3(\counter[0] ),
    .B1(rst),
    .X(_35_)
  );
  sky130_fd_sc_hd__nor2_2 _75_ (
    .A(_34_),
    .B(_35_),
    .Y(_02_)
  );
  sky130_fd_sc_hd__a31oi_2 _76_ (
    .A1(\counter[2] ),
    .A2(\counter[1] ),
    .A3(\counter[0] ),
    .B1(\counter[3] ),
    .Y(_36_)
  );
  sky130_fd_sc_hd__and4_2 _77_ (
    .A(\counter[3] ),
    .B(\counter[2] ),
    .C(\counter[1] ),
    .D(\counter[0] ),
    .X(_37_)
  );
  sky130_fd_sc_hd__nor3_2 _78_ (
    .A(rst),
    .B(_36_),
    .C(_37_),
    .Y(_03_)
  );
  sky130_fd_sc_hd__a21oi_2 _79_ (
    .A1(\counter[4] ),
    .A2(_37_),
    .B1(rst),
    .Y(_38_)
  );
  sky130_fd_sc_hd__o21a_2 _80_ (
    .A1(\counter[4] ),
    .A2(_37_),
    .B1(_38_),
    .X(_04_)
  );
  sky130_fd_sc_hd__a21oi_2 _81_ (
    .A1(\counter[4] ),
    .A2(_37_),
    .B1(\counter[5] ),
    .Y(_39_)
  );
  sky130_fd_sc_hd__and3_2 _82_ (
    .A(\counter[5] ),
    .B(\counter[4] ),
    .C(_37_),
    .X(_40_)
  );
  sky130_fd_sc_hd__nor3_2 _83_ (
    .A(rst),
    .B(_39_),
    .C(_40_),
    .Y(_05_)
  );
  sky130_fd_sc_hd__and2_2 _84_ (
    .A(\counter[6] ),
    .B(_40_),
    .X(_41_)
  );
  sky130_fd_sc_hd__nor2_2 _85_ (
    .A(rst),
    .B(_41_),
    .Y(_42_)
  );
  sky130_fd_sc_hd__o21a_2 _86_ (
    .A1(\counter[6] ),
    .A2(_40_),
    .B1(_42_),
    .X(_06_)
  );
  sky130_fd_sc_hd__a21oi_2 _87_ (
    .A1(\counter[7] ),
    .A2(_41_),
    .B1(rst),
    .Y(_43_)
  );
  sky130_fd_sc_hd__o21a_2 _88_ (
    .A1(\counter[7] ),
    .A2(_41_),
    .B1(_43_),
    .X(_07_)
  );
  sky130_fd_sc_hd__dfxtp_2 _89_ (
    .CLK(clk),
    .D(_00_),
    .Q(\counter[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _90_ (
    .CLK(clk),
    .D(_01_),
    .Q(\counter[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _91_ (
    .CLK(clk),
    .D(_02_),
    .Q(\counter[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _92_ (
    .CLK(clk),
    .D(_03_),
    .Q(\counter[3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _93_ (
    .CLK(clk),
    .D(_04_),
    .Q(\counter[4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _94_ (
    .CLK(clk),
    .D(_05_),
    .Q(\counter[5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _95_ (
    .CLK(clk),
    .D(_06_),
    .Q(\counter[6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _96_ (
    .CLK(clk),
    .D(_07_),
    .Q(\counter[7] )
  );
endmodule
